spring:
  jpa:
    generate-ddl: true
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: sa
    driverClassName: org.h2.Driver
